// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnmIRVoTtetzJDYC8LJ08PAtoKukyFjg4',
    appId: '1:399157408032:web:eb6cefe1e7da42f457e745',
    messagingSenderId: '399157408032',
    projectId: 'intern-go-ai',
    authDomain: 'intern-go-ai.firebaseapp.com',
    storageBucket: 'intern-go-ai.firebasestorage.app',
    measurementId: 'G-WH034HXF6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvjhnGrQpaUjYTJoC5nTxzu4FEDunYChA',
    appId: '1:399157408032:android:6126b20000498b7757e745',
    messagingSenderId: '399157408032',
    projectId: 'intern-go-ai',
    storageBucket: 'intern-go-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3dDK45bVAtE5wmnynQb6ZmmWq1ctAJ3A',
    appId: '1:399157408032:ios:d7e81b12af4c3b6757e745',
    messagingSenderId: '399157408032',
    projectId: 'intern-go-ai',
    storageBucket: 'intern-go-ai.firebasestorage.app',
    iosBundleId: 'com.example.internGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3dDK45bVAtE5wmnynQb6ZmmWq1ctAJ3A',
    appId: '1:399157408032:ios:d7e81b12af4c3b6757e745',
    messagingSenderId: '399157408032',
    projectId: 'intern-go-ai',
    storageBucket: 'intern-go-ai.firebasestorage.app',
    iosBundleId: 'com.example.internGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnmIRVoTtetzJDYC8LJ08PAtoKukyFjg4',
    appId: '1:399157408032:web:85028498632748de57e745',
    messagingSenderId: '399157408032',
    projectId: 'intern-go-ai',
    authDomain: 'intern-go-ai.firebaseapp.com',
    storageBucket: 'intern-go-ai.firebasestorage.app',
    measurementId: 'G-WC8T1R0FCD',
  );
}
